// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QSMPDLE.Web.Infrastructure.Persistence;

#nullable disable

namespace QSMPDLE.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QSMPDLE.Web.Features.Gameplay.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffiliationsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affiliations");

                    b.Property<string>("AliasesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aliases");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<int?>("JoinDayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("join_day_number");

                    b.Property<int>("Languages")
                        .HasColumnType("integer")
                        .HasColumnName("languages");

                    b.Property<string>("MinecraftUsername")
                        .HasColumnType("text")
                        .HasColumnName("minecraft_username");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_url");

                    b.Property<string>("PronounsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pronouns");

                    b.Property<string>("SpeciesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Gameplay.Models.DailyGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyGames");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameGuess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("GuessOrder")
                        .HasColumnType("integer");

                    b.Property<int>("GuessedCharacterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameGuess");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DailyNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWon")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetCharacterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameStats", t =>
                        {
                            t.HasCheckConstraint("CK_GameStats_PlayerId_NotEmpty", "\"PlayerId\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Gameplay.Models.DailyGame", b =>
                {
                    b.HasOne("QSMPDLE.Web.Features.Gameplay.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameGuess", b =>
                {
                    b.HasOne("QSMPDLE.Web.Features.Statistics.Models.GameSession", "GameSession")
                        .WithMany("Guesses")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameSession", b =>
                {
                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
