// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QSMPDLE.Web.Infrastructure.Persistence;

#nullable disable

namespace QSMPDLE.Web.Migrations.TelemetryDb
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameGuess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuessOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuessedCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameGuess");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameStats");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameGuess", b =>
                {
                    b.HasOne("QSMPDLE.Web.Features.Statistics.Models.GameSession", "GameSession")
                        .WithMany("Guesses")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Statistics.Models.GameSession", b =>
                {
                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
