// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QSMPDLE.Web.Infrastructure.Persistence;

#nullable disable

namespace QSMPDLE.Web.Migrations
{
    [DbContext(typeof(GameplayDbContext))]
    partial class GameplayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QSMPDLE.Web.Features.Gameplay.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AffiliationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("affiliations");

                    b.Property<string>("AliasesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aliases");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_url");

                    b.Property<int?>("JoinDayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("join_day_number");

                    b.Property<int>("Languages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("languages");

                    b.Property<string>("MinecraftUsername")
                        .HasColumnType("TEXT")
                        .HasColumnName("minecraft_username");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("page_url");

                    b.Property<string>("PronounsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pronouns");

                    b.Property<string>("SpeciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Gameplay.Models.DailyGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyGames");
                });

            modelBuilder.Entity("QSMPDLE.Web.Features.Gameplay.Models.DailyGame", b =>
                {
                    b.HasOne("QSMPDLE.Web.Features.Gameplay.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
